### ISSUE TITLE
confirm or update license

### ISSUE THREAD

**Issue by gkiar** [verificarlo/fuzzy#14]

**Comment by gkiar** [comment]
I would like to update the License to MIT because GPL is prohibitive (I know of at least one org who wants to use this but can't because current version is GPL), but the main verificarlo project is GPL so we can't. @pablooliveira @yohanchatelain @glatard  what are your thoughts on this?

**Comment by pablooliveira** [comment]
Dear @gkiar. 

I'm not sure I agree with the negative connotation of the term _prohibitive_; many would argue that the GPL is indeed _freeing_ since it ensures that the code stays open, free and shared among all ;-)

Nevertheless, I understand that many companies are not confortable using GPL. I am personally ok relicensing in a more permissive licence such as MIT but it's not a simple process.

Verificarlo chose the GPL licence historically because it was built upon Frechtling's mcalib, which is itself GPL. So we had no choice. Nowadays, we have completely rewritten the mca backend, so we could imagine removing mcalib-mpfr backend and relicence.

But relicensing, requires the agreement of all current and past Verificarlo contributors, which can be a lenghty process. I know that @titeup was also interested in relicensing Verificarlo. Maybe it is time to start this process ?

**Comment by titeup** [comment]
Hello all,
Indeed, GPL is preventing many usage because of the linking mechanism we are using. It is also not compatible with LLVM licensing policy to become part of the official release. As @pablooliveira says, this was an historical choice and could be now change with the agreement of all contributors. 
What we can do is call for a meeting and invite all contributors to discuss relicensing possibilities. Since this is an LLVM tool, I was thinking to use open license that are compatible with LLVM policy. (BSD is fine if I remember correctly).Maybe we can have a first meeting to discuss proposals we can make and gather legal info before doing the general meeting.

**Comment by pablooliveira** [comment]
Do you think we can do this asynchrously @titeup ? Decide here, what license would be appropriate for our uses. Then write a mail to all contributors to ask for agreement or veto ?

**Comment by gkiar** [comment]
Thanks for the quick responses, @pablooliveira @titeup ! Given timezone differences it may be better to find an asynchronous way to relicense. Perhaps something as simple as a google form (eg) with a few options including BSD, MIT, Apache, or GPL (unchanged), and a short blurb as to why the change is proposed in the first place.

**Comment by pablooliveira** [comment]
Dear both. The LLVM license situation is complex (the project is itself undergoing a relicensing). 
I see two possible licenses for Verificarlo:
- BSD
- Or the new LLVM license (Apache 2 + more permissive clauses) https://llvm.org/docs/DeveloperPolicy.html#new-llvm-project-license-framework

@gkiar: would both these licenses work for you ?

@titeup since I know you were interested in upstreaming parts of Verificarlo at some point, I would like your input on the licence. In your opinion, should we go with BSD or the new LLVM license ?

**Comment by gkiar** [comment]
Hi @pablooliveira, thanks for looking into this! Both BSD and an Apache+ license would work for the use cases I'm considering. I defer to you and @titeup for a more specific determination on what makes sense for us.

Thanks again

**Comment by pablooliveira** [comment]
For simplicity's sake, I would like to avoid having two separate licenses for Frontends and Backends.
I would also like to avoid having to go through the relicensing process twice.

If BSD is fine for you, then let's pick that. But if you think, BSD might be a problem for later upstreaming the frontend; maybe we should pick Apache 2.0 + LLVM exceptions instead.

**Comment by pablooliveira** [comment]
The Apache 2.0 + LLVM exceptions, license is available here: https://foundation.llvm.org/relicensing/LICENSE.txt
For all practical matters it should be compatible with BSD. I think the main difference is that it offers more protection against software patents litigations; which should not affect us since we are in Europe.

**Comment by titeup** [comment]
I read the LLVM license project. I am not a legal person, but I believe that if BSD is compatible and less restrictive it is the best option. Secondly, if this license is still a project, it means that later changes will require us to restart the process since the license leaves the copyright to original authors. If you agree, I think we can start writing down the email with a sample  of the future license and copyright file and explanation to send to all contributors and get their consent. I will send a first draft to @pablooliveira for doublechecking that I did not forget any useful information and proceed.

**Comment by pablooliveira** [comment]
That's fine; I also would favor « Apache 2.0 + LLVM » to simplify future integration ! Thanks for the first draft.

**Comment by titeup** [comment]
WIP: https://github.com/verificarlo/verificarlo/issues/231

**Comment by titeup** [comment]
Hi @gkiar, all, 
we finally complete the process on verificarlo side and change to:  Apache License v2.0 with LLVM Exceptions.
@yohanchatelain is fixing the sigdigits part and you will be good to go if you still want to change your license!

**Comment by titeup** [comment]
> The significantdigits license has been updated, can we close the issue? [verificarlo/significantdigits/pull/20](https://github.com/verificarlo/significantdigits/pull/20)

Yes I think so, @gkiar has now all he needs to proceed.

**Comment by gkiar** [comment]
Excellent. Thank you, all!
